name: 'f1'
version: '1.0.0'
profile: 'f1'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  f1:
    staging:
      +schema: CLEANED           # staging models go to schema = staging
      +materialized:  view       # staging should be views

    marts:
      +schema: marts             # base schema for marts layer
      dimensions:
        +schema: dimension       # **this is where your dim tables will be**
        +materialized: table
      facts:
        +schema: fact            # fact tables
        +materialized: table
